#!/bin/bash
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
HOOKS_DIR=".git/hooks/pre-push.d"

for hook in "$HOOKS_DIR"/*; do
    "$hook"
    EXIT_CODE=$?

    if [ $EXIT_CODE != 0 ]; then
        echo "Pre-push hook failed: $hook"
        exit $EXIT_CODE
    fi
done

# Check for changes made by the hooks
if ! git diff-index --quiet HEAD --; then
    # Stage any changes
    git add -u

    # Amend the newly made commit with these changes
    git commit --amend --no-edit
fi

exit 0
